### PR TITLE
vendor: bump test-infra

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

```
go get k8s.io/test-infra
go mod download
go mod vendor
go mod tidy

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Part of DPTP-2042

**Comment by stevekuznetsov** [comment]
Looks like this was already up-to-date - @bradmwilliams you might want to add a presubmit here to enforce `go mod tidy`

**Comment by stevekuznetsov** [comment]
.... wait, this repo doesn't vendor test-infra?

**Comment by stevekuznetsov** [comment]
sigh
/close

**Comment by smarterclayton** [comment]
no one *wants* to vendor test-infra, they’re just young and impressionable

**Pull request closed without merging**
