### PR TITLE
Add crun support for cluster-bot

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

### CODE REVIEW

**Comment by harche** [comment]
PR for adding required variant - https://github.com/openshift/release/pull/23610

**Comment by bradmwilliams** [comment]
/hold
Wait for https://github.com/openshift/release/pull/23610 to merge

**Comment by harche** [comment]
> /hold Wait for [openshift/release#23610](https://github.com/openshift/release/pull/23610) to merge

/unhold since [openshift/release#23610](https://github.com/openshift/release/pull/23610) is merged.

**Pull request merged**
